### ISSUE TITLE
Update homepage content to reflect restructure

### ISSUE THREAD

**Issue by nickwynja** [infor-design/website#511]
Referencing update to "Components".

Please just add final content on this ticket to and it will be added to the homepage template.

**Comment by kmahsmith** [comment]
Final Content Below

Guidelines
Read about design best practices and principles when using fonts, colors, and components to assemble a page design.
CTA: Read Guidelines

Components 
Access detailed specs, code snippets and API’s on the different libraries supported within the Infor Design System.
CTA: View Components


This section will require a bit more than just copy changes. 
I think we can simplify "The Components" section. Since each section gets called out on the homepage, I think we can remove the "see how to build section" and keep the content focused on just the examples.

Examples
Learn about common layouts and pages designs within the CloudSuite that showcase the Infor Design System's best practices and components.
CTA: Learn More

![screen shot 2018-04-23 at 3 32 37 pm](https://user-images.githubusercontent.com/34688242/39148956-9d3d0642-470b-11e8-940c-ffa30469a3ee.png)
