### ISSUE TITLE
Markdown Bulleted List 

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/website#528]
Right now the bulleted list has a padding bottom of 8px. Can we remove so the line items are tighter together and feel more like a grouped item.

<img width="926" alt="screen shot 2018-05-02 at 11 41 43 am" src="https://user-images.githubusercontent.com/34688242/39533733-d55e1432-4dfd-11e8-800a-51163b8fb744.png">

<img width="967" alt="screen shot 2018-05-02 at 11 42 35 am" src="https://user-images.githubusercontent.com/34688242/39533777-f4360180-4dfd-11e8-9b59-9fa0829a16ec.png">

**Comment by nickwynja** [comment]
Sure, but this change was introduced from #388. Can you and @kayiuho make sure you're on the same page here?

**Comment by kmahsmith** [comment]
Looks the original request was for "change children line items (everything except for item with accordion) padding top and bottom to be 8px"

Is the concern that by removing the padding bottom we break our rules?

**Comment by nickwynja** [comment]
Oops, wrong ticket. I meant #460 "Add padding-bottom: 8px to li's". Nope, no issues with the change. I agree that it makes them look too separated right now but know that this had been an intentional change in the first place so wanted to double check about going back on it (which I'm fine with here).

**Comment by kmahsmith** [comment]
Ya, I think we should go back to no padding bottom on child line items - bulleted section

**Comment by kayiuho** [comment]
I'm cool with that.
