### ISSUE TITLE
'What is your title?' sticky banner 

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#552]
- [x] design for sticky banner asking title 
Potentially use design similar to this: http://ant.design/components/mention/ (bottom right)
     - Design
     - Developer
     - BA
     - Product manager 
     - Other 

- [ ] Rick to come up with tracking URL/plan to make sure we can capture their usage post entering their title
- [ ] dev to implement onto site

**Comment by kmahsmith** [comment]
what do you guys think for copy? any ideas?
"Tell us who you are"
" What's your role"

**Comment by tmcconechy** [comment]
2cents

Tell us a bit about your self?
Whats your Role? (Role maybe better than title as its possibly more inline with web dev roles vs titles that may be more flat)

**Comment by kayiuho** [comment]
Mocks for "what's your role?" on content pages:
- A sticky button with a "person" icon
- Once clicked, a "popover" shows with radio selection of a primary role (since there are people who wear more than one hat)
- Once submitted, it displays a quick "Thank you" feedback and reminder to sign up for Newsletter

Let me know your thoughts!

<img width="1440" alt="screen shot 2018-05-29 at 4 57 59 pm" src="https://user-images.githubusercontent.com/34747859/40692244-a6040854-637e-11e8-8ac8-3949478df4b1.png">

<img width="1439" alt="screen shot 2018-05-29 at 4 57 00 pm" src="https://user-images.githubusercontent.com/34747859/40692247-a8b94cda-637e-11e8-8155-f517acd63fba.png">

<img width="1436" alt="screen shot 2018-05-29 at 4 57 19 pm" src="https://user-images.githubusercontent.com/34747859/40692248-aaabe1ec-637e-11e8-9e0b-4dc3806d32e5.png">

**Comment by kmahsmith** [comment]
Looking good! 

I'm not sure about this particular person icon - the way its positioned on the page makes it feel more of a chatbot or help area. Maybe a more stylizing icon or a question mark or something? 

Do you think we need a drop shadow on the blue icon on static too?

**Comment by kayiuho** [comment]
- Updated from the person to a "?"
- Added a hyperlink inside the popover that will take users to the NL sign up form on the bottom

Any other design feedback?

![screen shot 2018-05-30 at 3 20 49 pm](https://user-images.githubusercontent.com/34747859/40742634-238b8826-641d-11e8-8781-e052046a364a.png)

![screen shot 2018-05-30 at 3 21 02 pm](https://user-images.githubusercontent.com/34747859/40742638-264c2520-641d-11e8-950d-d7a74ad768c5.png)

![screen shot 2018-05-30 at 3 21 12 pm](https://user-images.githubusercontent.com/34747859/40742645-28e2f002-641d-11e8-9f02-866165f55b35.png)

![screen shot 2018-05-30 at 3 21 22 pm](https://user-images.githubusercontent.com/34747859/40742651-2b4f8db4-641d-11e8-99bc-4fb3518d3120.png)

**Comment by swetteinfor** [comment]
for this we won't do a "viewed event" because it happens on every page and we can just assume the total user count has seen the icon.

 **when user clicks the popup icon**
` ga(‘send’, ‘event’, ‘feedback’, ‘click | hover' , 'whatisyourrole' );'
 

 **when user submits the role**
`
  ga(‘send’, ‘event’, ‘feedback’, ‘submittedrole' , 'whatisyourrole' {'dimension8': '[selected role]'} ); `

**Comment by kayiuho** [comment]
Here you go @jmacaluso711 
[icons_help_close.zip](https://github.com/infor-design/website/files/2076687/icons_help_close.zip)
