### ISSUE TITLE
Implement a url status alert tool

### ISSUE THREAD

**Issue by clepore** [infor-design/website#696]
**Is your feature request related to a problem? Please describe.**
If any of the urls go down, we need to know about it.

**Describe the solution you'd like**
- Investigate and implement a tool like [Pingdom](https://www.pingdom.com/)
- maybe add a status page to see when things are up/down

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by clepore** [comment]
For now I used Uptime Robot to monitor the urls:
- https://design.infor.com/
- http://master-enterprise.demo.design.infor.com/
- http://latest-enterprise.demo.design.infor.com/

Status page here: https://stats.uptimerobot.com/7XrlQI7ZG.

I'm game for other ideas, possible through AWS? @corpulent @rmchale000 ? @lucacolumbu

**Comment by lucacolumbu** [comment]
I think we should test AWS CloudWatch, it has a generous free tier, and it's already automatically sending data from EC2 instances, for what I understand.
- https://aws.amazon.com/cloudwatch/

**Comment by tmcconechy** [comment]
We also have some involvement in the Company with https://statuscast.com/
This is the status cast page for Infor Cloud suite: https://inforcloudsuite.statuscast.com/#!/

I knew this because i saw there is a PDF design for it on https://jira.infor.com/browse/UXD-96 and some Infor contacts that me be able to ask questions to about it.
