### ISSUE TITLE
Need a way to download all icons.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/website#712]
**Describe the bug**

Neither the page on https://design.infor.com/code/ids-enterprise/latest/icons nor https://design.infor.com/guidelines/identity/icons mentions the codified SVG components but some teams would like to download the individual icons.

Secondly if Manilla design makes icons how do they get into this zip and the codified SVG 's.

**Expected behavior**

Provide a link to download a zip of all svg and png icons in a set. or describe how to get them out of a sketch or whatever may be most appropriate. 

**Additional context**

This was asked by a few team members.
CC Lothar Blum && John McGown

**Workaround**
- go to 4.6 where it has all the images in a folder https://github.com/infor-design/enterprise/tree/4.6.x
- click download as zip
- look in the images folder of the zip
- this may be missing newer icons

**Comment by tmcconechy** [comment]
Part is related to https://github.com/infor-design/design-system/issues/197

**Comment by clepore** [comment]
We have a ticket (https://github.com/infor-design/design-system/issues/247) in progress in the design system repo to take the master sketch file (also in the repo), convert it to a folder of all SVG icons in the `dist/` directory, and publish it to NPM and be available on in the downloadable [releases here](https://github.com/infor-design/design-system/releases).

This comment should link the tickets so every one interested can check the status of those tickets as we go along.

**Comment by nickwynja** [comment]
We've updated the assets which get pushed to the docs API. Navigating to https://staging.design.infor.com/api/docs/ids-identity/2.1.0/ gets you this:

```json
{
    "files": [
        "api/docs/ids-identity/2.1.0/tokens/",
        "api/docs/ids-identity/2.1.0/theme-uplift/",
        "api/docs/ids-identity/2.1.0/theme-soho/",
        "api/docs/ids-identity/2.1.0/sketch/"
    ]
}
```
Through this, you get `api/docs/ids-identity/2.1.0/theme-soho/icons/standard/metadata.json` which is an object of categories and icons which live in a sub-directory like `theme-soho/icons/standard/svg/`.

I think for this, we'd want to create a streamfield object for icons where you can write a "type" in a field. The "type" would correspond with the directory under `theme-soho/icons/` where the `metadata.json` lives. The client would then render an `icons-lookup` component when it sees this icon streamfield object coming back from the API and the angular component can handle getting the `metadata.json` from the endpoint, loop through it, and render the icons.

**Comment by nickwynja** [comment]
A few things we still need to do with this:

- [ ] Add in-page search/filter by name
- [ ] Add download option for each icon
- [ ] Add "download all" link to Github release zip

**Comment by nickwynja** [comment]
We've got this built out but need some help refining the design. @kayiuho @beccakroll @kentonquatman, anyone want to take a stab?

![screen shot 2019-02-13 at 4 51 57 pm](https://user-images.githubusercontent.com/1012017/52746577-d3c20180-2faf-11e9-8181-023c17b57fdf.png)

![screen shot 2019-02-13 at 4 52 03 pm](https://user-images.githubusercontent.com/1012017/52746581-d6245b80-2faf-11e9-95b3-c045ae35b3e7.png)


Any design updates should cover these parts:

- The field is a filter that matches the icon name and reduces the list as you type
- The SVG and PNG links are to download the asset
- There's a link at the bottom of the list (could be placed on top as well) which is just arbitrary content within the CMS

**Comment by kayiuho** [comment]
I can take a look today and "jazz" it up!

**Comment by kayiuho** [comment]
- Having a single filter/search across sets would be ideal. Users might not know or even care where the icon I'm looking for is located, it's double work when they have to search twice. If we can't combine the search for now, Command+F would be faster.
- Add icon set titles? (Standard, Extended, Empty State)
- Add `margin-bottom: 1rem` to icon name
- Show 24px instead of 32px? 32 seems big when they sit in a group
- Page reorg? Intro guidelines > Link to full set in Code > Icon visuals (w/ or w/o filter) > Visual Usage (tokens) > Rest of the guidelines

<img width="924" alt="screen shot 2019-02-14 at 5 03 28 pm" src="https://user-images.githubusercontent.com/34747859/52820975-7f845380-307b-11e9-9987-b487bf2795e1.png">

**Comment by nickwynja** [comment]
@jmacaluso711 I've pushed some CSS changes to the `724-ui-changes` branch around this. There's one additional change I couldn't immediately figure out. Can you please update the branch so that the `<icon-download>` links only show on `icon-card` hover? This should reduce the clutter of all the links repeating.

**Comment by nickwynja** [comment]
This is available on production now at https://design.infor.com/guidelines/identity/icons
